###
### Variables
###

# Global variables (will be set in every job):
variables:
  WARN_AS_ERROR: "1"
  # MAKEFLAGS: "-s"
  REALM_BACKTRACE: "1"
  REALM_SYNTHETIC_CORE_MAP: "" # Disable Realm thread pinning.

# Local variables (included on a case-by-case basis in each job):
.gcc48: &gcc48
  CXX: "g++-4.8"
.gcc49: &gcc49
  CXX: "g++-4.9"
.gcc5: &gcc5
  CXX: "g++-5"
.gcc6: &gcc6
  CXX: "g++-6"

.clang35: &clang35
  CXX: "clang++-3.5"
.clang38: &clang38
  CXX: "clang++-3.8"

.terra35: &terra35
  LLVM_CONFIG: "llvm-config-3.5"
  TERRA_DIR: "/usr/local/terra35"
.terra38: &terra38
  LLVM_CONFIG: "llvm-config-3.8"
  TERRA_DIR: "/usr/local/terra38"

.debug: &debug
  DEBUG: "1"
.release: &release
  DEBUG: "0"

.cxx98_normal: &cxx98_normal
  CC_FLAGS: "-std=c++98"
.cxx98_checks: &cxx98_checks
  CC_FLAGS: "-std=c++98 -DPRIVILEGE_CHECKS -DBOUNDS_CHECKS"
.cxx98_spy: &cxx98_spy
  CC_FLAGS: "-std=c++98 -DLEGION_SPY"
  USE_SPY: "1"
.cxx11_normal: &cxx11_normal
  CC_FLAGS: "-std=c++11"
.cxx98_32bit_normal: &cxx98_32bit_normal
  CC_FLAGS: "-std=c++98 -m32"
  LD_FLAGS: "-m32"
  MARCH: "i686"

.hdf5: &hdf5
  USE_HDF: "1"
.gasnet: &gasnet
  USE_GASNET: "1"
.cmake: &cmake
  USE_CMAKE: "1"

.skip_regent: &skip_regent
  TEST_REGENT: "0"

###
### Setup
###

# These commands will run before each job.
before_script:
  - uname -a
  - |
    if [[ "$(uname)" = "Linux" ]]; then
      export THREADS=$(nproc --all)
    elif [[ "$(uname)" = "Darwin" ]]; then
      export THREADS=$(sysctl -n hw.ncpu)
    else
      echo "Unknown platform. Setting THREADS to 1."
      export THREADS=1
    fi
  # - |
  #   if [[ "$(uname)" = "Darwin" ]]; then
  #     brew update
  #     brew install pypy homebrew/versions/llvm35
  #   fi
  - |
    if [[ "$USE_GASNET" -eq 1 ]]; then
      export CONDUIT=mpi
      export GASNET_ROOT="$PWD/gasnet/release"
      export LAUNCHER="mpirun -n 2 -x TERRA_PATH -x INCLUDE_PATH -x LD_LIBRARY_PATH -x LG_RT_DIR -x USE_RDIR"
      unset WARN_AS_ERROR
      git clone https://github.com/StanfordLegion/gasnet.git gasnet
      pushd gasnet
      make -j$THREADS
      popd
    fi

###
### Tags
###

.linux: &linux
  tags:
    - linux
.macos: &macos
  tags:
    - macos

# For compute-heavy tests:
.linux_compute: &linux_compute
  tags:
    - linux
    - compute

###
### Docker Image
###

# Each job will run in a fresh container with this image.
.image: &image
  image: stanfordlegion/gitlab-ci # i.e. https://hub.docker.com/r/stanfordlegion/gitlab-ci/

###
### Tests
###

# Each job will run this set of tests.
.tests: &tests
  script:
    - ./test.py

# Some additional tests are only run on certain configurations.
.external_tests: &external_tests
  script:
    - |
      if [[ -n $GITLAB_DEPLOY_KEY ]]; then
        eval $(ssh-agent -s)
        ssh-add <(echo "$GITLAB_DEPLOY_KEY")
        mkdir -p ~/.ssh
        [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      fi
    - ./test.py --test=external --test=private

###
### Jobs
###

# Each item below defines a job.

# There are two tiers of tests.
#  1. Full test suite (small number of compilers).
#  2. Minimal test suite (other compilers).

# Run the full test suite on GCC 4.9 and Clang 3.5.

# Linux with GCC 4.9
linux_gcc49_terra35_cxx98_release:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *release, *cxx98_normal]
linux_gcc49_terra35_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_checks]
linux_gcc49_terra35_cxx98_debug_spy:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_spy]
linux_gcc49_terra35_cxx11_release:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *release, *cxx11_normal]
linux_gcc49_terra35_cxx98_debug_checks_hdf5:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_checks, *hdf5]
linux_gcc49_terra35_cxx98_debug_checks_gasnet:
  <<: [*linux_compute, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_checks, *gasnet]
linux_gcc49_terra35_cxx98_32bit_debug_noregent:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_32bit_normal, *skip_regent]
linux_gcc49_terra35_cxx98_debug_checks_cmake_noregent:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_checks, *cmake, *skip_regent]
linux_gcc49_terra35_cxx98_debug_checks_external:
  <<: [*linux_compute, *image, *external_tests]
  variables:
    <<: [*gcc49, *terra35, *debug, *cxx98_checks]

# Linux with Clang 3.5
linux_clang35_terra35_cxx98_release:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *release, *cxx98_normal]
linux_clang35_terra35_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_checks]
linux_clang35_terra35_cxx98_debug_spy:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_spy]
linux_clang35_terra35_cxx11_release:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *release, *cxx11_normal]
linux_clang35_terra35_cxx98_debug_checks_hdf5:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_checks, *hdf5]
# # FIXME: Clang with GASNet freezes
# linux_clang35_terra35_cxx98_debug_checks_gasnet:
#   <<: [*linux_compute, *image, *tests]
#   variables:
#     <<: [*clang35, *terra35, *debug, *cxx98_checks, *gasnet]
linux_clang35_terra35_cxx98_32bit_debug_noregent:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_32bit_normal, *skip_regent]
linux_clang35_terra35_cxx98_debug_checks_cmake_noregent:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_checks, *cmake, *skip_regent]
linux_clang35_terra35_cxx98_debug_checks_external:
  <<: [*linux_compute, *image, *external_tests]
  variables:
    <<: [*clang35, *terra35, *debug, *cxx98_checks]

# # macOS with Clang 3.5
# macos_clang35_cxx98_debug_checks:
#   <<: [*macos, *tests]
#   variables:
#     <<: [*clang35, *debug, *cxx98_checks]

# Run minimal tests on other compilers.

# Linux with GCC 4.8, 5, 6
linux_gcc48_terra35_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc48, *terra35, *debug, *cxx98_checks]
linux_gcc5_terra35_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc5, *terra35, *debug, *cxx98_checks]
linux_gcc6_terra35_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*gcc6, *terra35, *debug, *cxx98_checks]

# Linux with Clang 3.8
linux_clang38_terra38_cxx98_debug_checks:
  <<: [*linux, *image, *tests]
  variables:
    <<: [*clang38, *terra38, *debug, *cxx98_checks]
